version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.2-jdk-8-slim
    environment:
    branches:
      ignore:
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "Building"
          command: mvn clean install
      - run:
          name: "Deploying"
          command: mvn -s .circleci/settings.xml deploy
