version: 2
jobs:
  build:
    docker:
      - image: maven:3.9-eclipse-temurin-17
    environment:
    branches:
      ignore:
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "Building"
          command: mvn clean install
